name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Test, build and release new version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Paprika 🌶
        run: npm run build

      - name: Run tests
        run: npm test --if-present

      # - name: Prepare build artifacts
      #   run: |
      #     zip paprika-tween.zip CHANGELOG.md README.md package.json -r dist docs

      - name: Create release
        uses: cycjimmy/semantic-release-action@v3
        with:
          dry_run: false
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/exec
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
